apiVersion: v1
kind: Pod
metadata:
    name: postgress-pod
    labels:
        name: postgress-pod
        app: voting-app-demo
spec:
    containers:
        - name: postgres
          image: postgres
          ports:
             - containerPort: 5432