apiVersion: v1
kind: Pod
metadata:
    name: redis-pod
    labels:
        name: redis-pod
        app: voting-app-demo
spec:
    containers:
        - name: redis
          image: redis
    Ports:
        - containerPort: 6379