apiVersion: v1
kind: Pod
metadata:
    name: vote-app-pod
    labels: 
        name: vote-app-pod
        app: voting-app-demo
spec:
    containers:
       - name: vote-app
         image: dockersamples/examplevotingapp_vote